src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Validator\Constraints as AppAssert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ServiceRepository::class)
 */
#[UniqueEntity('name')]
#[Assert\EnableAutoMapping]
class Service implements \Stringable
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=255, unique=true)
     */
    #[Assert\NotBlank]
    private string $name;

    /**
     * @ORM\Column(type="smallint", options={"unsigned":true})
     */
    #[Assert\Positive]
    private int $hours;

    /**
     * @ORM\Column(type="smallint", options={"unsigned":true})
     */
    #[Assert\Positive]
    #[Assert\Expression("value <= this.getHours()", message: 'Hours on premises >= total hours')]
    private int $hoursOnPremises;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $category;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
//    #[Assert\NotBlank(message: 'Service steps must be defined')]
    private ?array $steps = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     */
//    #[Assert\NotBlank(message: 'Service reasons must be defined')]
    private ?array $reasons = [];

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $expectations;

    /**
     * Date before which this service should not be performed.
     *
     * @ORM\Column(type="date", nullable=true)
     */
    #[AppAssert\DateTimeUTC]
    private ?\DateTimeInterface $fromDate;

    /**
     * Date after which this service should not be performed.
     *
     * @ORM\Column(type="date", nullable=true)
     */
    #[AppAssert\DateTimeUTC]
    private ?\DateTimeInterface $toDate;

    /**
     * @ORM\Column(type="smallint", options={"unsigned":true}, nullable=true)
     */
    private ?int $taskPreferredOnPremisesHours;

    public function getName(): string
    {
        return $this->name;
    }
    public function getNameWithoutPrefix(): ?string
    {
        return preg_replace('/^\d+\.\s+/i', '', $this->name);
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getHours(): int
    {
        return $this->hours;
    }

    public function setHours(int $hours): self
    {
        $this->hours = $hours;
        return $this;
    }

    public function getHoursOnPremises(): int
    {
        return $this->hoursOnPremises;
    }

    public function setHoursOnPremises(int $hoursOnPremises): self
    {
        $this->hoursOnPremises = $hoursOnPremises;
        return $this;
    }

    #[Assert\Expression("value == (this.getHours() - this.getHoursOnPremises())", message: 'Remote hours added to on-premises does not match total hours')]
    public function getHoursRemote(): int
    {
        return $this->hours - $this->getHoursOnPremises();
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;
        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): self
    {
        $this->category = $category;
        return $this;
    }

    public function getSteps(): ?array
    {
        return $this->steps;
    }

    public function setSteps(?array $steps): self
    {
        $this->steps = $steps;
        return $this;
    }

    public function getReasons(): array
    {
        return $this->reasons;
    }

    public function setReasons(?array $reasons): self
    {
        $this->reasons = $reasons;
        return $this;
    }

    public function getExpectations(): string
    {
        return $this->expectations;
    }

    public function setExpectations(?string $expectations): self
    {
        $this->expectations = $expectations;
        return $this;
    }

    public function getFromDate(): ?\DateTimeInterface
    {
        return $this->fromDate;
    }

    public function setFromDate(?\DateTimeInterface $from): self
    {
        $this->fromDate = $from;
        return $this;
    }

    public function getToDate(): ?\DateTimeInterface
    {
        return $this->toDate;
    }

    public function setToDate(?\DateTimeInterface $to): self
    {
        $this->toDate = $to;
        return $this;
    }

    public function getTaskPreferredOnPremisesHours(): ?int
    {
        return $this->taskPreferredOnPremisesHours;
    }

    public function setTaskPreferredOnPremiseSHours(?int $taskPreferredOnPremisesHours): self
    {
        $this->taskPreferredOnPremisesHours = $taskPreferredOnPremisesHours;
        return $this;
    }

    public function __toString(): string
    {
        return $this->getName();
    }
}

templates/app.html.twig
<!DOCTYPE html>
<html lang="it-IT">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Conagrivet Gestionale</title>

        <link rel="icon" href="data:">
        <link rel="api" href="//{{ app.request.getHttpHost() }}/api/v1/" />

        <!-- Highcharts -->
        <script src="https://code.highcharts.com/highcharts.src.js"></script>
        <script src="https://code.highcharts.com/modules/accessibility.src.js"></script>
        <script src="https://code.highcharts.com/modules/heatmap.src.js"></script>
        <script src="https://code.highcharts.com/modules/exporting.src.js"></script>
        <script src="https://code.highcharts.com/modules/offline-exporting.src.js"></script>

        <!-- Fullcalendar -->
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.6.0/main.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.6.0/locales-all.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.6.0/main.min.css">

        <!-- App  -->
        {% for script in scripts %}
            <script type="module" src="/{{ base }}/{{ script.getRelativePathname() }}"></script>
        {% endfor %}

        {% for style in styles %}
            <link rel="stylesheet" href="/{{ base }}/assets/styles/{{ style.relativePathname }}">
        {% endfor %}
    </head>

    <body></body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/contract.html.twig
<!DOCTYPE html>
<html lang="it-IT">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Contratto {{ recipient.name }}</title>

        <link rel="stylesheet" href="{{ asset(base ~ '/styles/contracts.css') }}">

        <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>

    </head>
    <body>
        <main id="content">

            <article class="contract">
                <h1>
                    PSR Toscana 2014/2020<br/>
                    Sottomisura 2.1 “Sostegno ad avvalersi ai servizi di consulenza”<br/>
                    cup artea n&deg; 901854
                </h1>

                <section class="parties">
                    <p>Il giorno
                        <input class="fill-blank" type="text" size="4" />
                        del mese di
                        <input class="fill-blank" type="text" size="17" />
                        dell'anno
                        <input class="fill-blank" type="text" size="6" />
                        fra le parti:
                    </p>

                    <ul class="no-style">
                        <li>CONAGRIVET S.R.L. con sede legale in 53048 Sinalunga (SI), Via Faustina e Pietro Zappalorto n. 1 int. 8/C, C.F. e P.IVA 01487210526, in persona del Presidente del Consiglio di Amministrazione e Direttore Tecnico del progetto Per. Agr. Fiorenzo Belelli, nato a Castiglion Fiorentino (AR) il 23 gennaio 1973, C.F. BLLFNZ73A23C319W e domiciliato per la carica in 53048 Sinalunga (SI), Via Faustina e Pietro Zappalorto n. 1 int. 8/C, di seguito per brevità indicato come “soggetto fornitore del servizio di consulenza”;</li>
                        <li>
                            Sig./Sig.ra <input class="fill-blank" type="text" size="79"><br>
                            nato/a <input class="fill-blank" type="text" size="53" placeholder="San Valentino in Abruzzo Citeriore">
                            il <input class="fill-blank" type="text" size="15">
                            in qualità di titolare/legale rappresentante della ditta denominata {{ recipient.name|upper }}
                            con sede legale in <input class="fill-blank" type="text" size="76" placeholder="Via Dietro a San Michele dei Leprosetti, 123/B, 33020, San Valentino in Abruzzo Citeriore"><br>
                            ed operativa in <input class="fill-blank" type="text" size="74" placeholder="Via Dietro a San Michele dei Leprosetti, 123/B, 33020, San Valentino in Abruzzo Citeriore"> ,<br>

                            {% if not recipient.fiscalCode is empty %}
                            C.F. {{ recipient.fiscalCode|upper }},
                            {% endif %}

                            {% if not recipient.vatId is empty %}
                            P.IVA {{ recipient.vatId|upper }},
                            {% endif %}

                            iscritta alla Camera di Commercio di <input class="fill-blank" type="text" size="30" placeholder="verbano cusio ossola" /> ,
                            di seguito per brevità indicato come “destinatario finale del servizio di consulenza”;</li>
                    </ul>
                    <p>
                        dato atto che il servizio di consulenza sotto specificato beneficia di contributo del FEASR - Misura 2 PSR 2014-2020 della Regione Toscana, il destinatario finale del servizio di consulenza, con la sottoscrizione del presente contratto, conferisce al soggetto fornitore del servizio di consulenza formale incarico per la prestazione dei seguenti servizi di consulenza:
                    </p>
                </section>

                {% for service in services %}
                <section class="service">
                    <h2>servizio di consulenza {{ service.service.nameWithoutPrefix }}</h2>

                    <h3>Tematica e percorso di consulenza</h3>
                    <p><b>{{ service.service.category }}</b></p>

                    <h3>Descrizione sintetica del servizio</h3>
                    <p>{{ service.service.description |nl2br }}</p>

                    <h3>Motivazioni che rendono necessaria la consulenza</h3>
                    <ul>
                        {% for reason in service.service.reasons %}
                        <li>{{ reason|nl2br }}</li>
                        {% endfor %}
                    </ul>

                    <h3>Fasi della consulenza</h3>
                    <ol class="no-style">
                        {% for step in service.service.steps %}
                            <li>{{ step |nl2br }}</li>
                        {% endfor %}
                    </ol>

                    <section class="consultants">
                        <h3>Indicazione dei consulenti coinvolti</h3>
                        <ul class="consultants">
                            <li>
                                <span class="title">{{ service.consultant.title }}</span>
                                <span class="name">{{ service.consultant.name | upper }}</span>
                                {%- if not service.consultant.jobTitle is empty -%}
                                    , <span class="job">{{ service.consultant.jobTitle }}</span>
                                {% endif %}
                            </li>
                        </ul>
                    </section>

                    <section class="expectations">
                        <h3>Risultati attesi</h3>
                        <p>{{ service.service.expectations |nl2br }}</p>
                    </section>

                    <section class="hours">
                        <h3>Ore di lavoro necessarie</h3>
                        <p>N. {{ service.service.hours }} ore di cui n. {{ service.service.hoursOnPremises }} ore da svolgere in presenza del destinatario finale del servizio di consulenza.</p>
                    </section>

                </section>
                {% endfor %}

                <section class="general">
                    <h2>condizioni generali</h2>

                    <h3>Tempi di svolgimento delle attività</h3>
                    <p>Dalla data di sottoscrizione del presente contratto, fino al giorno 01 marzo 2022. Le attività non potranno iniziare prima delle ore 8.00 e non potranno terminare dopo le ore 18.00, esclusi i giorni festivi e prefestivi.</p>

                    <h3>Onere finanziario complessivo, escluso oneri di legge</h3>
                    <p>L'onere complessivo dei servizi offerti ammonta a {{ amount |format_currency('EUR', locale='it') }}, di cui {{ amount_financed |format_currency('EUR', locale='it') }} sono a carico del destinatario finale dei servizi di consulenza.</p>

                    <h3>Modalità di pagamento</h3>
                    <p>
                        Vista fattura a mezzo bonifico bancario c/o BANCA CENTRO Credito Cooperativo Toscana – Umbria IBAN  IT65I0707572040000000722321, causale 'SALDO FATTURA N.
                        <input class="fill-blank" type="text" size="9">
                        DEL
                        <input class="fill-blank" type="text" size="15">
                        CUP ARTEA N. 901854'</p>

                    <h3>Dichiarazioni</h3>
                    <p>Il destinatario finale del servizio di consulenza dichiara:</p>
                    <ul>
                        <li>che non è stato superato il massimale di contributo FEASR per servizi di consulenza fissato in euro 4.500 nell’arco dell’intero periodo di programmazione e che, in caso di dichiarazione non veritiera, il contributo non sarà riconosciuto e dovrà egli sostenere per intero il costo dell’attività di consulenza;</li>
                        <li>di non essere impresa in difficoltà (art. 1, co. 6 del Reg. 702/2014) e di essere in regola con le disposizioni in materia di aiuti di stato (clausola Deggendorf) e che, in caso di dichiarazione non veritiera, il contributo non sarà riconosciuto e dovrà egli sostenere per intero il costo dell’attività di consulenza.</li>
                    </ul>

                    <h3>Disposizioni finali</h3>
                    <p>Il soggetto fornitore del servizio di consulenza garantirà la registrazione e la descrizione delle attività svolte da parte dei consulenti coinvolti nelle attività con specifica indicazione delle ore di lavoro svolte in presenza del destinatario finale. I consulenti dovranno pertanto redigere il time-sheet di riferimento, mentre il destinatario finale del servizio di consulenza dovrà attestare mediante apposita documentazione, da conservare in copia in azienda, le ore di lavoro svolte in sua presenza con la descrizione delle attività effettuate. Almeno il 30% delle attività di consulenza dovranno essere svolte in presenza del destinatario finale del singolo servizio di consulenza.</p>
                    <p>Il presente contratto decorre ed ha efficacia dalla data di sua sottoscrizione da ambo le parti. Per quanto qui non esplicitamente riportato si fa riferimento a quanto previsto nel codice civile agli artt. 2222 e successivi e dalle altre disposizioni di legge che risultino applicabili. In caso di eventuali controversie legali inerente e conseguenti a quanto stabilito con il presente contratto, è competente il Foro di Siena.</p>

                    <h3>Informativa e consenso al trattamento dei dati (Reg. UE n. 679/2016 “GDPR”)</h3>
                    <p>Il destinatario finale del servizio di consulenza abilita ed autorizza espressamente il soggetto fornitore del servizio di consulenza e in ogni caso i suoi collaboratori, i dipendenti, i Professionisti o Società allo stesso collegati/e e/o quanti ne abbiano titolo, a richiedere, divulgare, consegnare, inviare, ritirare e in ogni caso ad aver accesso a richiedere e/o consegnare documentazioni e informazioni, relativi alla propria persona e/o azienda presso qualunque ufficio o ente sia pubblico che privato. L’autorizzazione viene concessa per l’espletamento dell’incarico ricevuto con la sottoscrizione del presente contratto ed estesa a tutti i dati ordinari e non di cui al Regolamento (UE) n. 679/2016 (“GDPR”).</p>
                </section>

                <section class="signatures">
                    <p class="location">
                        Letto, confermato e sottoscritto il <input class="fill-blank" type="text" size="15">
                        a <input class="fill-blank" type="text" size="43"> .
                    </p>

                    <div class="signatures">
                        <div class="conagrivet">
                            <p>(Il soggetto fornitore del servizio di consulenza)</p>
                            <p>p. CONAGRIVET S.r.l.</p>
                            <p>Il Presidente del C.d.A.</p>
                            <p>Per. Agr. Fiorenzo Belelli</p>
                            <img src="{{ asset('/images/signature-fiorenzo.png') }}" width="1981" height="805" />
                            <input class="fill-blank" type="text" />
                        </div>
                        <div class="recipient">
                            <p>(Il destinatario finale del servizio di consulenza)</p>
                            <p>TIMBRO E FIRMA</p>
                            <input class="fill-blank" type="text" />
                        </div>
                    </div>
                </section>

            </article>
        </main>
    </body>
</html>

templates/contracts-list.html.twig
<!DOCTYPE html>
<html lang="it-IT">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Conagrivet Contracts</title>
    </head>
    <body>
        <main id="content">
            <ul>
                {% for recipient in recipients %}
                {% set tax_id = recipient.vatId ?? recipient.fiscalCode %}
                <li>
                    <a href="{{ path('contracts_recipient', {taxId: tax_id}) }}">{{ tax_id }}</a>  {{ recipient.name }}
                </li>
                {% endfor %}
            </ul>
        </main>
    </body>
</html>

templates/schedule-all.twig
<!DOCTYPE html>
<html lang="it-IT">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Programmazione consulenze in presenza</title>

        <link rel="stylesheet" href="{{ asset(base ~ '/styles/schedule.css') }}">

        <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
    </head>
    <body>
        <header id="header">
            <h1>Domanda PSR 2014-2020 - Misura 2.1 &ndash; “Sostegno ad avvalersi di servizi di consulenza”</h1>

            <h2>Progetto SERVIZI DI CONSULENZA CONAGRIVET SRL - PROGETTO 2020 CUP ARTEA N. 901854</h2>

            <h3>Comunicazione ai sensi dell'Art. 2 “Impegni a carico del beneficiario fino al saldo dei contributi”, punto II) “Condizioni di ammissibilità dei servizi di consulenza” lettera b), del Contratto di Assegnazione del contributo.</h3>
        </header>

        <main id="content">

            {% for consultant in consultants %}
            <article class="consultant">
                <header>
                    <h1>
                        <span class="name">{{ consultant.name | upper }}</span>
                        <span class="job">{{ consultant.job }}</span>
                        <span class="hours">{{ consultant.hours_on_premises }} ore in presenza</span>
                    </h1>
                </header>

                <div class="tasks">
                    <div class="headings">
                        <span>data</span>
                        <span>orario</span>
                        <span>destinatario</span>
                        <span>luogo</span>
                    </div>

                    {% for task in consultant.tasks %}
                    <div class="task">
                        <span>{{ task.date }}</span>
                        <span>{{ task.start }} - {{ task.end }}</span>
                        <span>{{ task.recipient }}</span>
                        <span>c/o U.T.E. azienda</span>
                    </div>
                    {% endfor %}
                </div>

            </article>
            {% endfor %}

        </main>
    </body>
</html>

templates/schedule-consultant.twig
<!DOCTYPE html>
<html lang="it-IT">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Programmazione consulenze in presenza</title>

        <link rel="stylesheet" href="{{ asset(base ~ '/styles/schedule.css') }}">

        <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
    </head>
    <body>
        <header id="header">
            <h1>Domanda PSR 2014-2020 - Misura 2.1 &ndash; “Sostegno ad avvalersi di servizi di consulenza”</h1>

            <h2>{{ consultant.name |upper }}</h2>

{#            <h3>Programmazione preventiva ore in presenza</h3>#}
        </header>

        <main id="content">
            <article class="consultant">
                <header>
                    <h1>
                        <span class="name">{{ consultant.name | upper }}</span>
                        <span class="job">{{ consultant.jobTitle }}</span>
                        <span class="hours">{{ hours_on_premises }} ore in presenza</span>
                    </h1>
                </header>

                <div class="tasks">
                    <div class="headings">
                        <span>data</span>
                        <span>orario</span>
                        <span>destinatario</span>
                        <span>luogo</span>
                    </div>

                    {% for task in tasks %}
                    <div class="task">
                        <span>{{ task.date }}</span>
                        <span>{{ task.start }} - {{ task.end }}</span>
                        <span>{{ task.recipient }}</span>
                        <span>c/o U.T.E. azienda</span>
                    </div>
                    {% endfor %}
                </div>

            </article>
        </main>
    </body>
</html>

templates/schedule.twig
<!DOCTYPE html>
<html lang="it-IT">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Programmazione consulenze in presenza</title>

        <link rel="stylesheet" href="{{ asset(base ~ '/assets/styles/schedule.css') }}">

        <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
    </head>
    <body>
        <header id="header">
            <h1>Domanda PSR 2014-2020 - Misura 2.1 &ndash; “Sostegno ad avvalersi di servizi di consulenza”</h1>

            <h2>Progetto SERVIZI DI CONSULENZA CONAGRIVET SRL - PROGETTO 2020 CUP ARTEA N. 901854</h2>

            <h3>Comunicazione ai sensi dell'Art. 2 “Impegni a carico del beneficiario fino al saldo dei contributi”, punto II) “Condizioni di ammissibilità dei servizi di consulenza” lettera b), del Contratto di Assegnazione del contributo.</h3>
        </header>

        <main id="content">

            {% for consultant in consultants %}
            <article class="consultant">
                <header>
                    <h1>
                        <span class="name">{{ consultant.name | upper }}</span>
                        <span class="job">{{ consultant.job }}</span>
                        <span class="hours">{{ consultant.hours_on_premises }} ore in presenza</span>
                    </h1>
                </header>

                <div class="tasks">
                    <div class="headings">
                        <span>data</span>
                        <span>orario</span>
                        <span>destinatario</span>
                        <span>luogo</span>
                    </div>

                    {% for task in consultant.tasks %}
                    <div class="task">
                        <span>{{ task.date }}</span>
                        <span>{{ task.start }} - {{ task.end }}</span>
                        <span>{{ task.recipient }}</span>
                        <span>c/o U.T.E. azienda</span>
                    </div>
                    {% endfor %}
                </div>

            </article>
            {% endfor %}

        </main>
    </body>
</html>

templates/schedules-list.twig
<!DOCTYPE html>
<html lang="it-IT">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>Elenco Programmazioni</title>
    </head>
    <body>
        <main id="content">
            <ul>
            {% for schedule in schedules %}
                <li><a href="/schedules/{{ schedule.id }}">{{ schedule.consultant.name }}</a></li>
            {% endfor %}
            </ul>
        </main>
    </body>
</html>